config/routes.rb
Rails.application.routes.draw do
  resources :pets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = %w(reptile feline canine bird horse)
  validates :name, presence: true
  validates :address, presence: true
  validates :species, inclusion: { in: SPECIES }

  # found_on => Date class!
  def days_ago
    (Date.today - self.found_on).to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [ :show, :edit, :update, :destroy ]

  def index
    @pets = Pet.all
  end

  def show
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @pet.update(pet_params)
      redirect_to pet_path(@pet)
    else
      render :edit
    end
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :address, :species, :found_on)
  end

  def set_pet
    @pet = Pet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pets/_form.html.erb
<%= simple_form_for @pet do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :species, collection: Pet::SPECIES %>
  <%= f.input :found_on %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/pets/edit.html.erb
<div class="card">
  <%= render 'form' %>
</div>

app/views/pets/index.html.erb
<%= link_to "Add a found pet", new_pet_path %>
<ul>
  <% @pets.each do |pet| %>
    <div class="card">
      <h1 class="p-3"><%= link_to pet.name, pet_path(pet) %></h1>
      <h2 class="p-3">Found <%= pet.days_ago %> days ago</h2>
      <p class="p-3"><%= pet.address  %></p>
      <p class="p-3"><%= pet.species %></p>
    </div>
  <% end %>
</ul>

app/views/pets/new.html.erb
<div class="card">
  <%= render 'form' %>
</div>

app/views/pets/show.html.erb
<h1><%= @pet.name %> <small>(<%= @pet.species %>)</small></h1>
<ul>
  <li>🏡 Address: <%= @pet.address %></li>
  <li>📅 Found <%= @pet.days_ago %> days ago!</li>
</ul>

<%= link_to "Go back home!", pets_path %>
<%= link_to "Found its owner", pet_path(@pet), method: :delete, data: {confirm: "Are you sure? Really, really sure?"} %>